# Generated by Django 5.1.4 on 2026-05-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LichHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_hoc', models.CharField(max_length=100, verbose_name='Môn học')),
                ('ma_lop', models.CharField(max_length=20, verbose_name='Mã lớp')),
                ('ngay_hoc', models.DateField(verbose_name='Ngày học')),
                ('tiet_bat_dau', models.PositiveIntegerField(verbose_name='Tiết bắt đầu')),
                ('tiet_ket_thuc', models.PositiveIntegerField(verbose_name='Tiết kết thúc')),
                ('si_so', models.PositiveIntegerField(default=30, verbose_name='Sĩ số')),
                ('trang_thai', models.CharField(choices=[('hoat_dong', 'Hoạt động'), ('da_huy', 'Đã hủy')], default='hoat_dong', max_length=20, verbose_name='Trạng thái')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Lịch học',
                'verbose_name_plural': 'Lịch học',
                'db_table': 'lich_hoc',
                'ordering': ['ngay_hoc', 'tiet_bat_dau'],
            },
        ),
    ]
