# Generated by Django 5.1.4 on 2026-05-11 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LichHoc', '0001_initial'),
        ('PhongHoc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lichhoc',
            name='giang_vien',
            field=models.ForeignKey(limit_choices_to={'vai_tro': 'giang_vien'}, on_delete=django.db.models.deletion.CASCADE, related_name='lich_day', to=settings.AUTH_USER_MODEL, verbose_name='Giảng viên'),
        ),
        migrations.AddField(
            model_name='lichhoc',
            name='phong_hoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_hocs', to='PhongHoc.phonghoc', verbose_name='Phòng học'),
        ),
    ]
