# Generated by Django 5.1.4 on 2026-05-11 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LichHoc', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_lop', models.CharField(max_length=50, unique=True, verbose_name='Tên lớp')),
                ('khoa', models.CharField(blank=True, max_length=100, verbose_name='Khoa')),
                ('nien_khoa', models.CharField(blank=True, max_length=20, verbose_name='Niên khóa')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
                'db_table': 'lop_hoc',
            },
        ),
        migrations.AlterField(
            model_name='lichhoc',
            name='ma_lop',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mã lớp (Hiển thị)'),
        ),
        migrations.AddField(
            model_name='lichhoc',
            name='lop_hoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lich_hocs', to='LichHoc.lophoc', verbose_name='Lớp học'),
        ),
    ]
