# Generated by Django 5.1.4 on 2026-05-12 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LichHoc', '0003_lophoc_alter_lichhoc_ma_lop_lichhoc_lop_hoc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DangKyHocPhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dang_ky', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('lop_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dang_ky_hoc_phans', to='LichHoc.lophoc', verbose_name='Lớp học phần')),
                ('sinh_vien', models.ForeignKey(limit_choices_to={'vai_tro': 'sinh_vien'}, on_delete=django.db.models.deletion.CASCADE, related_name='dang_ky_hoc_phans', to=settings.AUTH_USER_MODEL, verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Đăng ký học phần',
                'verbose_name_plural': 'Đăng ký học phần',
                'db_table': 'dang_ky_hoc_phan',
                'ordering': ['-ngay_dang_ky'],
                'unique_together': {('sinh_vien', 'lop_hoc')},
            },
        ),
    ]
