# Generated by Django 5.1.4 on 2026-05-12 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LichHoc', '0004_dangkyhocphan'),
        ('PhongHoc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YeuCauDoiLich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_yeu_cau', models.CharField(choices=[('doi_phong', 'Đổi phòng học'), ('doi_gio', 'Đổi giờ/tiết học'), ('huy_buoi', 'Hủy buổi học'), ('khac', 'Khác')], max_length=20, verbose_name='Loại yêu cầu')),
                ('ly_do', models.TextField(verbose_name='Lý do yêu cầu')),
                ('ngay_moi', models.DateField(blank=True, null=True, verbose_name='Ngày mới')),
                ('tiet_moi_bat_dau', models.IntegerField(blank=True, null=True, verbose_name='Tiết bắt đầu mới')),
                ('tiet_moi_ket_thuc', models.IntegerField(blank=True, null=True, verbose_name='Tiết kết thúc mới')),
                ('trang_thai', models.CharField(choices=[('cho_duyet', 'Chờ duyệt'), ('da_duyet', 'Đã duyệt'), ('tu_choi', 'Từ chối')], default='cho_duyet', max_length=20, verbose_name='Trạng thái')),
                ('ghi_chu_duyet', models.TextField(blank=True, verbose_name='Ghi chú duyệt')),
                ('ngay_duyet', models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('lich_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeu_cau_doi_lichs', to='LichHoc.lichhoc', verbose_name='Lịch học gốc')),
                ('nguoi_duyet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yeu_cau_duyet', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('nguoi_yeu_cau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeu_cau_gui', to=settings.AUTH_USER_MODEL, verbose_name='Người yêu cầu')),
                ('phong_moi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yeu_cau_doi_phongs', to='PhongHoc.phonghoc', verbose_name='Phòng mới (nếu đổi phòng)')),
            ],
            options={
                'verbose_name': 'Yêu cầu đổi lịch',
                'verbose_name_plural': 'Yêu cầu đổi lịch',
                'db_table': 'yeu_cau_doi_lich',
                'ordering': ['-ngay_tao'],
            },
        ),
    ]
