# Generated by Django 5.1.4 on 2026-05-13 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LichHoc', '0005_yeucaudoilich'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon', models.CharField(max_length=100, verbose_name='Tên môn học')),
                ('ma_mon_hoc', models.CharField(max_length=20, unique=True, verbose_name='Mã học phần')),
                ('so_tin_chi', models.PositiveIntegerField(default=3, verbose_name='Số tín chỉ')),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
                'db_table': 'mon_hoc',
            },
        ),
        migrations.RemoveField(
            model_name='lichhoc',
            name='lop_hoc',
        ),
        migrations.RemoveField(
            model_name='lichhoc',
            name='giang_vien',
        ),
        migrations.RemoveField(
            model_name='lichhoc',
            name='ma_lop',
        ),
        migrations.RemoveField(
            model_name='lichhoc',
            name='mon_hoc',
        ),
        migrations.RemoveField(
            model_name='lichhoc',
            name='si_so',
        ),
        migrations.CreateModel(
            name='LopHocPhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_lop_hoc_phan', models.CharField(max_length=50, unique=True, verbose_name='Mã lớp học phần')),
                ('hoc_ky', models.PositiveIntegerField(default=1, verbose_name='Học kỳ')),
                ('nam_hoc', models.CharField(default='2023-2024', max_length=20, verbose_name='Năm học')),
                ('si_so_toi_da', models.PositiveIntegerField(default=40, verbose_name='Sĩ số tối đa')),
                ('giang_vien', models.ForeignKey(limit_choices_to={'vai_tro': 'giang_vien'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lop_hoc_phans', to=settings.AUTH_USER_MODEL, verbose_name='Giảng viên')),
                ('mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lop_hoc_phans', to='LichHoc.monhoc', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Lớp học phần',
                'verbose_name_plural': 'Lớp học phần',
                'db_table': 'lop_hoc_phan',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dangkyhocphan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dangkyhocphan',
            name='lop_hoc_phan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dang_ky_sinh_viens', to='LichHoc.lophocphan', verbose_name='Lớp học phần'),
        ),
        migrations.AddField(
            model_name='lichhoc',
            name='lop_hoc_phan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lich_hocs', to='LichHoc.lophocphan', verbose_name='Lớp học phần'),
        ),
        migrations.AlterUniqueTogether(
            name='dangkyhocphan',
            unique_together={('sinh_vien', 'lop_hoc_phan')},
        ),
        migrations.RemoveField(
            model_name='dangkyhocphan',
            name='lop_hoc',
        ),
        migrations.DeleteModel(
            name='LopHoc',
        ),
    ]
