# Generated by Django 5.1.4 on 2026-05-13 03:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LichHoc', '0006_monhoc_remove_lichhoc_lop_hoc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichhoc',
            name='lop_hoc_phan',
        ),
        migrations.AlterModelOptions(
            name='monhoc',
            options={'ordering': ['ma_mon'], 'verbose_name': 'Môn học', 'verbose_name_plural': 'Môn học'},
        ),
        migrations.RemoveField(
            model_name='monhoc',
            name='ma_mon_hoc',
        ),
        migrations.AddField(
            model_name='lichhoc',
            name='giang_vien',
            field=models.ForeignKey(default=1, limit_choices_to={'vai_tro': 'giang_vien'}, on_delete=django.db.models.deletion.CASCADE, related_name='lich_day', to=settings.AUTH_USER_MODEL, verbose_name='Giảng viên'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lichhoc',
            name='ma_lop',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mã lớp hiển thị'),
        ),
        migrations.AddField(
            model_name='lichhoc',
            name='mon_hoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lich_hocs', to='LichHoc.monhoc', verbose_name='Môn học'),
        ),
        migrations.AddField(
            model_name='lichhoc',
            name='si_so',
            field=models.PositiveIntegerField(default=30, verbose_name='Sĩ số'),
        ),
        migrations.AddField(
            model_name='monhoc',
            name='ma_mon',
            field=models.CharField(default='TEMP', max_length=20, unique=True, verbose_name='Mã học phần'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monhoc',
            name='ngay_tao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='ten_mon',
            field=models.CharField(max_length=150, verbose_name='Tên môn học'),
        ),
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_lop', models.CharField(max_length=50, unique=True, verbose_name='Tên lớp học phần')),
                ('khoa', models.CharField(blank=True, max_length=100, verbose_name='Khoa quản lý')),
                ('nien_khoa', models.CharField(blank=True, max_length=20, verbose_name='Học kỳ/Niên khóa')),
                ('mon_hoc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lop_hoc_phans', to='LichHoc.monhoc', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Lớp học phần',
                'verbose_name_plural': 'Lớp học phần',
                'db_table': 'lop_hoc',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dangkyhocphan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dangkyhocphan',
            name='lop_hoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dang_ky_hoc_phans', to='LichHoc.lophoc', verbose_name='Lớp học phần'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lichhoc',
            name='lop_hoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lich_hocs', to='LichHoc.lophoc', verbose_name='Lớp học phần'),
        ),
        migrations.AlterUniqueTogether(
            name='dangkyhocphan',
            unique_together={('sinh_vien', 'lop_hoc')},
        ),
        migrations.RemoveField(
            model_name='dangkyhocphan',
            name='lop_hoc_phan',
        ),
        migrations.DeleteModel(
            name='LopHocPhan',
        ),
    ]
