# Generated by Django 5.1.4 on 2026-05-13 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LichHoc', '0007_remove_lichhoc_lop_hoc_phan_alter_monhoc_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lophoc',
            name='giang_vien',
            field=models.ForeignKey(blank=True, limit_choices_to={'vai_tro': 'giang_vien'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lop_phu_trach', to=settings.AUTH_USER_MODEL, verbose_name='Giảng viên phụ trách'),
        ),
    ]
