# Generated by Django 5.1.4 on 2026-05-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhongHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_phong', models.CharField(max_length=20, unique=True, verbose_name='Mã phòng')),
                ('ten_phong', models.CharField(max_length=100, verbose_name='Tên phòng')),
                ('toa_nha', models.CharField(max_length=50, verbose_name='Tòa nhà')),
                ('suc_chua', models.PositiveIntegerField(default=30, verbose_name='Sức chứa')),
                ('loai_phong', models.CharField(choices=[('ly_thuyet', 'Lý thuyết'), ('thuc_hanh', 'Thực hành'), ('hoi_truong', 'Hội trường')], default='ly_thuyet', max_length=20, verbose_name='Loại phòng')),
                ('trang_thai', models.CharField(choices=[('trong', 'Trống'), ('dang_su_dung', 'Đang sử dụng'), ('bao_tri', 'Bảo trì')], default='trong', max_length=20, verbose_name='Trạng thái')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Phòng học',
                'verbose_name_plural': 'Phòng học',
                'db_table': 'phong_hoc',
                'ordering': ['toa_nha', 'ma_phong'],
            },
        ),
    ]
