# Generated by Django 5.1.4 on 2026-05-11 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('noi_dung', models.TextField(verbose_name='Nội dung')),
                ('loai', models.CharField(choices=[('doi_phong', 'Đổi phòng'), ('doi_lich', 'Đổi lịch'), ('huy_lich', 'Hủy lịch'), ('bao_tri', 'Bảo trì')], default='doi_lich', max_length=20, verbose_name='Loại')),
                ('da_doc', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_bao_da_tao', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'db_table': 'thong_bao',
                'ordering': ['-ngay_tao'],
            },
        ),
    ]
