# Generated by Django 5.1.4 on 2026-05-11 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThongBao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thongbao',
            name='nguoi_nhan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thong_bao_cua_toi', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận'),
        ),
    ]
