# Generated by Django 5.1.4 on 2026-05-11 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PhongHoc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThietBi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_thiet_bi', models.CharField(max_length=100, verbose_name='Tên thiết bị')),
                ('trang_thai', models.CharField(choices=[('hoat_dong', 'Hoạt động'), ('hong', 'Hỏng'), ('bao_tri', 'Bảo trì')], default='hoat_dong', max_length=20, verbose_name='Trạng thái')),
                ('so_luong', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('phong_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhongHoc.phonghoc', verbose_name='Phòng học')),
            ],
            options={
                'verbose_name': 'Thiết bị',
                'verbose_name_plural': 'Thiết bị',
                'db_table': 'thiet_bi',
                'ordering': ['phong_hoc', 'ten_thiet_bi'],
            },
        ),
        migrations.CreateModel(
            name='BaoHong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mo_ta', models.TextField(verbose_name='Mô tả lỗi')),
                ('trang_thai', models.CharField(choices=[('cho_xu_ly', 'Chờ xử lý'), ('dang_sua', 'Đang sửa'), ('da_sua', 'Đã sửa')], default='cho_xu_ly', max_length=20, verbose_name='Trạng thái')),
                ('ngay_bao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày báo')),
                ('nguoi_bao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người báo')),
                ('thiet_bi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThietBi.thietbi', verbose_name='Thiết bị')),
            ],
            options={
                'verbose_name': 'Báo hỏng',
                'verbose_name_plural': 'Báo hỏng',
                'db_table': 'bao_hong',
                'ordering': ['-ngay_bao'],
            },
        ),
    ]
