# Generated by Django 5.1.4 on 2026-05-11 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LichHoc', '0003_lophoc_alter_lichhoc_ma_lop_lichhoc_lop_hoc'),
        ('NguoiDung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='lop_hoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinh_viens', to='LichHoc.lophoc', verbose_name='Lớp học (Dành cho SV)'),
        ),
    ]
