# Generated by Django 5.1.4 on 2026-05-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NguoiDung', '0002_nguoidung_lop_hoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoidung',
            name='lop_hoc',
        ),
    ]
