# Generated by Django 5.1.4 on 2026-05-13 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NguoiDung', '0003_remove_nguoidung_lop_hoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='LopSinhHoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_lop', models.CharField(max_length=50, unique=True, verbose_name='Tên lớp sinh hoạt')),
                ('khoa_hoc', models.IntegerField(default=2021, verbose_name='Khóa học')),
                ('khoa_quan_ly', models.CharField(blank=True, max_length=100, verbose_name='Khoa quản lý')),
            ],
            options={
                'verbose_name': 'Lớp sinh hoạt',
                'verbose_name_plural': 'Lớp sinh hoạt',
                'db_table': 'lop_sinh_hoat',
            },
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='lop_sinh_hoat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinh_viens', to='NguoiDung.lopsinhhoat', verbose_name='Lớp sinh hoạt'),
        ),
    ]
